parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Discord\Discord:
        factory: [ 'App\Factory\DiscordFactory', 'getDiscord' ]
        arguments:
            $logger: '@monolog.logger.discord'

    Keepa\KeepaAPI:
        factory: [ 'App\Factory\KeepaAPIFactory', 'getKeepaAPI' ]

    App\Command\Discord\RunCommand:
        arguments:
            $receiver: '@messenger.transport.async'

    _instanceof:
        App\Discord\Command\AbstractDiscordCommand:
            tags:
                - { name: 'app.discord.command' }

        App\Discord\EventListener\AbstractDiscordListener:
            tags:
                - { name: 'app.discord.listener' }