parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Discord\Discord:
        factory: [ 'App\Factory\DiscordFactory', 'getDiscord' ]
        arguments:
            $discordBotToken: '%env(DISCORD_BOT_TOKEN)%'
            $logger: '@monolog.logger.discord'

    App\Business\ConfigBusiness:
        arguments:
            $configFilePath: '%kernel.project_dir%/data/configuration.yaml'

    Keepa\KeepaAPI:
        factory: [ 'App\Factory\KeepaAPIFactory', 'getKeepaAPI' ]
        arguments:
            $keepaToken: '%env(KEEPA_TOKEN)%'
    App\Command\RunCommand:
        arguments:
            $receiver: '@messenger.transport.async'

    _instanceof:
        App\Discord\Command\AbstractDiscordCommand:
            tags:
                - { name: 'app.discord.command' }

        App\Discord\EventListener\AbstractDiscordListener:
            tags:
                - { name: 'app.discord.listener' }