[supervisord]
nodaemon=true
logfile=/tmp/supervisord.log
loglevel=debug
user=root

[inet_http_server]
port=*:9001
username=supervisoruser
password=supervisorpass

[program:bot]
command=/usr/local/bin/php /app/bin/console app:discord:run
autostart=true
autorestart=true

[program:cron]
command=/usr/local/bin/php /app/bin/console messenger:consume scheduler_default
autostart=true
autorestart=true

[program:apache2]
command=/usr/sbin/apachectl -D FOREGROUND
autostart=true
autorestart=true